name: Agglo
favicon: null
layout_spectrum: 0.34357
typography_spectrum: 0.95495
title: Blockchain Advisory Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060c1a'
    - '#2c333d'
    - '#525963'
    - '#8c939b'
    - '#bec5cd'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
